name: Create Release
description: "Create release if one does not already exist."
inputs:
  tagValue:
    description: The release tag value.
    required: true
  repository:
    description: The repository release is in.
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Simple Shell Script
      id: checkTag
      shell: bash
      run: |
        .github/actions/release/release.sh ${{ inputs.tagValue }} ${{ inputs.repository }}
    - name: Display Output
      shell: bash
      run: echo "${{ steps.checkTag.outputs.tagExists}}"
