name: Create Release Using Marketplace Actions
on:
  workflow_dispatch:
    inputs:
      tag_value:
        description: The tag value include 'v' prefix
        type: string
        required: true
        default: ""

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Release Action
        uses: ./.github/workflows/release
        with:
          tag_value: ${{ inputs.tag_value }}
          repository: $GITHUB_REPOSITORY

      - name: Check for Existing Release
        continue-on-error: true
        id: check-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view ${{inputs.tag_value }} \
          --repo="$GITHUB_REPOSITORY"

      - name: Display Output of previous step
        run: |
          echo ${{ steps.check-release.outputs }}
          echo ${{ steps.check-release.outcome}}
      # - name: Create Release
      #   id: create-release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: ${{ inputs.tag_value }}
      #     commit: ${{ github.sha }}
      #     generateReleaseNotes: true
      #     skipIfReleaseExists: true
