name: Failure Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy the lambda to."
        required: true
        default: "dev"
        type: environment
  push:
    branches:
      - main

jobs:
  failure:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || 'dev' }}
    steps:
      - name: Simple Echo Step
        run: echo "Yo!"

      - name: Fail using script
        if: ${{ github.ref != 'refs/heads/main' && inputs.environment == 'prod' }}
        uses: actions/github-script@v7
        with:
          script: core.setFailed('Release workflow can only be run on Main branch')

      - name: Verify Post Failure Skipped
        run: echo "Nope"
