name: Get Release By Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Value of tag"
        required: true
        type: string

permissions:
  contents: write

jobs:
  get-release-by-tag:
    name: Get Release By Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Release By Tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: "${{ github.event.inputs.tag }}"
            });
