name: Manually Triggered 2
on:
  workflow_dispatch:

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo '{"string":"prod", "number":7, "option":"Option 2", "environment":"production"}' | gh workflow run manually-triggered.yml --json
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
