name: Manually Triggered 2
on:
  workflow_dispatch:

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          gh workflow run manually-triggered.yml echo -f string="prod" -f number=7 -f option="Option 2" -f environment="production"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
