name: Manually Triggered 2
on:
  workflow_dispatch:

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF
      - run: |
          echo '{"string":"prod", "number":7, "option":"Option 2", "environment":"production"}' | gh workflow manually-triggered.yml --json
