name: Create Release

on: workflow_dispatch

permissions:
  contents: write

jobs:
  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"

      - name: Determine Version
        id: gitversion # id to later be referenced
        uses: gittools/actions/gitversion/execute@v0

      - name: Comment on New PRs
        uses: actions/github-script@v7
        env:
          TAG: "v${{ steps.gitversion.outputs.semVer }}"
        with:
          script: |
            // const { TAG } = process.env
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "v${{ steps.gitversion.outputs.semVer }}",
              name: "v${{ steps.gitversion.outputs.semVer }}",
              generate_release_notes: true,
            });
